markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
highlighter: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.sogou.com
title: wenwenfrontend's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: colin
email: lirui@sogou-inc.com
github: wenwenfrontend

config:
  js_dir:
  img_dir:
  css_dir:
